---
title: Covid-19 in Connecticut
subtitle: Data Visualizations
author:
  - David Braze
email: davebraze@gmail.com
institution: FDB Research
date: "`r format(Sys.time(), '%B %d, %Y')`"

# bibliography: ["al-report.bib"]
# biblio-style: "apalike"
# link-citations: true

always_allow_html: false
fontsize: 11pt
geometry: margin=1in
header-includes:
  - \usepackage{booktabs}

output:
  bookdown::tufte_html2:
    keep_md: true
    pandoc_args:
    - --lua-filter
    - "c:/Program Files/R/R-3.6.1/library/rmarkdown/rmd/lua/pagebreak.lua"

  bookdown::html_document2:
    keep_md: true
    theme: cerulean
    number_sections: no
    highlight: tango
    toc: yes
    toc_depth: 2
    toc_float: yes
    pandoc_args:
    - --lua-filter
    - "c:/Program Files/R/R-3.6.1/library/rmarkdown/rmd/lua/pagebreak.lua"
    
  bookdown::pdf_document2:
    keep_tex: true
    highlight: tango
    toc: yes
    number_sections: no
    pandoc_args:
    - --lua-filter
    - "c:/Program Files/R/R-3.6.1/library/rmarkdown/rmd/lua/pagebreak.lua"

---


```{r setup, echo=FALSE, include=FALSE}

## To render this document from a guaranteed clean R environment, use
## the provided Makefile.

## To load all objects referenced in this file into the current R
## environment, make the following call at the R prompt:

knitr::opts_chunk$set(fig.width=7,
                      fig.height=7/(16/9),
                      dpi=200,
                      tinytex.verbose=TRUE, ## PDFs very slow to compile.
                      echo=FALSE,
                      include=FALSE,
                      results='asis',
                      cache=TRUE,
                      warning=FALSE)

## Also see knitr::opts_current$get() within a chunk to inspect then-active options.

options(tinytex.verbose=TRUE,
        tinytex.clean=FALSE)

```


```{r workhorse}

source("./ct-covid.R")

```

# Read This First

```{r readme, include=TRUE}

cat(paste0(readLines("readme.md", n=-1), collapse="\n"))

```

# Show Me the Pictures

## Statewide Summary

```{r ct-stat-daily-change, include=TRUE, fig.height=7}

ct.stat.daily.change.plt

```

```{r usa-state-corona, include=TRUE}

usa.state.corona.plt

```


## Each Town

```{r town-rate, include=TRUE}

town.rate.plt

```

```{r town-by-county-rate, include=TRUE, fig.height=7}

town.by.county.rate.plt

```

```{r map-today, include=TRUE, fig.height=7}

map.today

```
