## Workflow derived from https://github.com/r-lib/actions/tree/master/examples
## via https://raw.githubusercontent.com/r-lib/actions/v1/examples/render-rmarkdown.yaml
## Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: "37 21 * * Mon-Fri" ## run at 21:37 UTC (5:37pm EST) Monday through Friday
      
  workflow_dispatch:
      
name: publish-new-data

jobs:
  update-data-and-publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2 # check out repo so gha job can access it
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-renv@v1

        ## The 'uses:' line below installs all R packages referenced in DEPENDENCIES file.
        ## That's good for an R package, not so much here (because no DEPENDENCIES file).
        ## So, I'm trying to use the 'install R packages' target to get that done.
        ## No success yet. Seems to work fine for libs w/o external dependencies, but
        ## fails on, e.g., RCurl. Would it help to force installation of binaries? Dunno.
        
      ## - uses: r-lib/actions/setup-r-dependencies@v2 
        
      - name: Install R packages
        run: |
          install.packages(c("rmarkdown", "bookdown", "httr", "XML", "here", "fs", "RCurl", "readr", "sf", "RSocrata"))
        shell: Rscript {0}
        
      - name: Do the thing
        run: |
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo ""
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          echo ""
          echo "> git config --list"
          git config --list
          echo ""
          echo "------------------------------------------------------"
          echo ""
          make publish
